Repository AICoE/integration-demo-summit-2022, pull requests merged in 2021-11, with the labels that each got.

#15 Add Microshift manifests
  apps/microshift/README.md
  apps/microshift/manifests/kubevirt-microshift-device.yaml
  apps/microshift/manifests/pvc-microshift-image.yaml
  apps/microshift/manifests/ssh-pod.yaml
Labels: approved, size/M

#21 Adding OWNERS file to /apps dir
  apps/OWNERS
Labels: approved, lgtm, size/S

#26 Update pipfile and .aicoe-ci for Thoth image build. Include simple donkeycar
  .aicoe-ci.yaml
  .pre-commit-config.yaml
  Pipfile
  Pipfile.lock
  apps/donkeycars/default_car/calibrate.py
  apps/donkeycars/default_car/config.py
  apps/donkeycars/default_car/manage.py
  apps/donkeycars/default_car/myconfig.py
  apps/donkeycars/default_car/train.py
Labels: approved, size/XXL
