Repository AICoE/integration-demo-summit-2022, pull requests merged in 2021-12, with the labels that each got.

#32 Suggest an update to the Owners file
  .thoth.yaml
  OWNERS
Labels: approved, size/XS

#31 initial toc and config for jupyterbook build
  Pipfile
  Pipfile.lock
  _config.yml
  _toc.yml
  apps/donkeycars/default_car/Download_Data.ipynb
Labels: size/L

#37 Update the Reviewers and fixed pre-commit
  .pre-commit-config.yaml
  .thoth.yaml
  OWNERS
Labels: approved, size/S
