Repository AICoE/integration-demo-summit-2022, pull requests merged in 2022-01, with the labels that each got.

#43 add donkey-gym to pipfiles
  Pipfile
  Pipfile.lock
Labels: size/XL

#46 donkeycar: initial Dockerfile build
  .aicoe-ci.yaml
  Dockerfile.donkey
Labels: approved, size/S

#49 Patch base-image for meteor to work with repo
  .aicoe-ci.yaml
Labels: approved, size/XS

#50 Setup delivery of image to the job
  .aicoe-ci.yaml
  .github/PULL_REQUEST_TEMPLATE.md
  .thoth.yaml
  OWNERS
  README.md
  app.py
  summit_2021_octo_keynote/__init__.py
  summit_2021_octo_keynote/version.py
  template/__init__.py
  templates/job.yaml
  templates/namespace.yaml
Labels: approved, size/M, lgtm

#55 donkey: update config
  apps/donkeycars/default_car/myconfig.py
Labels: lgtm, size/XS

#56 trained-model: Update job.yaml
  templates/job.yaml
Labels: approved, lgtm, size/XS

#64 Dockerfile: update to Fedora 35 base, removes unneeded baggage
  Dockerfile.donkey
  apps/donkeycars/default_car/launch_ai_car.sh
Labels: approved, lgtm, size/S
